// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductAndCategoryAPI.Data;

#nullable disable

namespace ProductAndCategoryAPI.Migrations
{
    [DbContext(typeof(ProductAndCategoryDbContext))]
    partial class ProductAndCategoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductAndCategoryAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Bread",
                            Description = "Freshly baked bread, whole wheat bread, baguettes."
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Cake slice",
                            Description = "Sliced cakes such as cheesecake, mousse, tiramisu."
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Savory",
                            Description = "Savory pastries like dumplings, meat pies, and quiches."
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Special",
                            Description = "Limited edition or seasonal special cakes and pastries."
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Sweet",
                            Description = "Sweet treats including cookies, macarons, and cupcakes."
                        });
                });

            modelBuilder.Entity("ProductAndCategoryAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic French croissant with buttery layers.",
                            ImageURL = "img/product/bread/croissant.png",
                            IsAvailable = true,
                            Price = 2.99m,
                            ProductName = "Croissant",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft bun filled with rich custard lava.",
                            ImageURL = "img/product/bread/goldenlavabun.png",
                            IsAvailable = true,
                            Price = 3.50m,
                            ProductName = "Golden Lava Bun",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fruit loaf packed with dried fruits and nuts.",
                            ImageURL = "img/product/bread/gourmetfruitloaf.png",
                            IsAvailable = true,
                            Price = 4.99m,
                            ProductName = "Gourmet Fruit Loaf",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Savory bread with a classic sausage filling.",
                            ImageURL = "img/product/bread/sausagestandard.png",
                            IsAvailable = true,
                            Price = 3.20m,
                            ProductName = "Sausage Standard",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Seasonal bread inspired by spring flavors.",
                            ImageURL = "img/product/bread/springinthecity.png",
                            IsAvailable = true,
                            Price = 5.00m,
                            ProductName = "Spring In The City",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chocolate cake with fresh berries topping.",
                            ImageURL = "img/product/cakeslice/bearychoco.png",
                            IsAvailable = true,
                            Price = 4.99m,
                            ProductName = "Berry Choco",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Creamy cheesecake layered with brownie crust.",
                            ImageURL = "img/product/cakeslice/browniecheesesliced.png",
                            IsAvailable = true,
                            Price = 5.50m,
                            ProductName = "Brownie Cheese Sliced",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cute bunny-shaped cake with vanilla flavor.",
                            ImageURL = "img/product/cakeslice/bunny.png",
                            IsAvailable = true,
                            Price = 6.00m,
                            ProductName = "Bunny",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chocolate mousse cake with peanut crunch.",
                            ImageURL = "img/product/cakeslice/bearyberry.png",
                            IsAvailable = true,
                            Price = 6.99m,
                            ProductName = "Chocolate Peanut Mousse",
                            StockQuantity = 18
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "French Opera cake with coffee and chocolate.",
                            ImageURL = "img/product/cakeslice/lesopera.png",
                            IsAvailable = true,
                            Price = 7.50m,
                            ProductName = "Les Opera Sliced",
                            StockQuantity = 22
                        },
                        new
                        {
                            ProductID = 11,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chocolate cheesecake topped with Oreo.",
                            ImageURL = "img/product/cakeslice/bearymatcha.png",
                            IsAvailable = true,
                            Price = 5.99m,
                            ProductName = "Oreo Chocolate Cheese",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductID = 12,
                            CategoryID = 3,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft chocolate-filled bun.",
                            ImageURL = "img/product/savory/chocolatebun.png",
                            IsAvailable = true,
                            Price = 3.50m,
                            ProductName = "Chocolate Bun",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductID = 13,
                            CategoryID = 3,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flaky croissant filled with rich chocolate.",
                            ImageURL = "img/product/savory/chocolatecroissant.png",
                            IsAvailable = true,
                            Price = 4.20m,
                            ProductName = "Chocolate Croissant",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductID = 14,
                            CategoryID = 3,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Japanese-style croissant with sesame flavor.",
                            ImageURL = "img/product/savory/gomacroissant.png",
                            IsAvailable = true,
                            Price = 4.50m,
                            ProductName = "Goma Croissant",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductID = 15,
                            CategoryID = 3,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Green tea-flavored bun with red bean filling.",
                            ImageURL = "img/product/savory/matchabun.png",
                            IsAvailable = true,
                            Price = 4.80m,
                            ProductName = "Matcha Bun",
                            StockQuantity = 18
                        },
                        new
                        {
                            ProductID = 16,
                            CategoryID = 3,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Extra chocolate-filled croissant.",
                            ImageURL = "img/product/savory/ultimatechococroissant.png",
                            IsAvailable = true,
                            Price = 5.20m,
                            ProductName = "Ultimate Choco Croissant",
                            StockQuantity = 22
                        },
                        new
                        {
                            ProductID = 17,
                            CategoryID = 3,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Croissant with smooth white chocolate filling.",
                            ImageURL = "img/product/savory/whitechococroissant.png",
                            IsAvailable = true,
                            Price = 4.90m,
                            ProductName = "White Choco Croissant",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductID = 18,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Luxurious French Opera cake with multiple layers.",
                            ImageURL = "img/product/cakeslice/lesopera.png",
                            IsAvailable = true,
                            Price = 8.99m,
                            ProductName = "Les Opera",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductID = 19,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Exotic mango and coconut-flavored cake.",
                            ImageURL = "img/product/special/mangocococake.png",
                            IsAvailable = true,
                            Price = 7.99m,
                            ProductName = "MangoCoCo Cake",
                            StockQuantity = 18
                        },
                        new
                        {
                            ProductID = 20,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vibrant pink cake perfect for celebrations.",
                            ImageURL = "img/product/special/partypink.png",
                            IsAvailable = true,
                            Price = 6.99m,
                            ProductName = "Party Pink",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductID = 21,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tangy passion fruit cheesecake.",
                            ImageURL = "img/product/special/passioncheese.png",
                            IsAvailable = true,
                            Price = 7.50m,
                            ProductName = "Passion Cheese",
                            StockQuantity = 18
                        },
                        new
                        {
                            ProductID = 22,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Colorful multi-layered sponge cake.",
                            ImageURL = "img/product/special/rainbow.png",
                            IsAvailable = true,
                            Price = 8.50m,
                            ProductName = "Rainbow",
                            StockQuantity = 12
                        },
                        new
                        {
                            ProductID = 23,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Winter-inspired cake with fruity layers.",
                            ImageURL = "img/product/special/snowyfruity.png",
                            IsAvailable = true,
                            Price = 7.20m,
                            ProductName = "Snowy Fruity",
                            StockQuantity = 16
                        },
                        new
                        {
                            ProductID = 24,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic Italian Tiramisu with coffee and mascarpone.",
                            ImageURL = "img/product/special/tiramisu.png",
                            IsAvailable = true,
                            Price = 7.99m,
                            ProductName = "Tiramisu",
                            StockQuantity = 14
                        },
                        new
                        {
                            ProductID = 25,
                            CategoryID = 5,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft donut covered in chocolate glaze.",
                            ImageURL = "img/product/sweet/chocolatedonut.png",
                            IsAvailable = true,
                            Price = 3.20m,
                            ProductName = "Chocolate Donut",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductID = 26,
                            CategoryID = 5,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chocolate-infused croffle with crispy texture.",
                            ImageURL = "img/product/sweet/chocolatedonut.png",
                            IsAvailable = true,
                            Price = 4.80m,
                            ProductName = "Croffle Chocolate Black",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductID = 27,
                            CategoryID = 5,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "White chocolate-coated croffle.",
                            ImageURL = "img/product/sweet/chocolatedonut.png",
                            IsAvailable = true,
                            Price = 4.50m,
                            ProductName = "Croffle Chocolate White",
                            StockQuantity = 28
                        },
                        new
                        {
                            ProductID = 28,
                            CategoryID = 5,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Caramel flan cake with creamy texture.",
                            ImageURL = "img/product/sweet/chocolatedonut.png",
                            IsAvailable = true,
                            Price = 5.50m,
                            ProductName = "Flan Cake",
                            StockQuantity = 22
                        },
                        new
                        {
                            ProductID = 29,
                            CategoryID = 5,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fluffy Japanese-style cheesecake.",
                            ImageURL = "img/product/sweet/chocolatedonut.png",
                            IsAvailable = true,
                            Price = 6.99m,
                            ProductName = "Japan Light Cheese",
                            StockQuantity = 18
                        });
                });

            modelBuilder.Entity("ProductAndCategoryAPI.Models.Product", b =>
                {
                    b.HasOne("ProductAndCategoryAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductAndCategoryAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
