// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderAPI.Data;

#nullable disable

namespace OrderAPI.Migrations
{
    [DbContext(typeof(OrderDBContext))]
    [Migration("20250719123646_dat")]
    partial class dat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderAPI.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            OrderDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending",
                            PaymentMethod = "Credit Card",
                            PaymentStatus = "Paid",
                            ShippingAddress = "Quận 12 - TP.HCM",
                            TotalAmount = 100m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 2,
                            OrderDate = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Shipped",
                            PaymentMethod = "COD",
                            PaymentStatus = "Pending",
                            ShippingAddress = "Quận 11 - TP.HCM",
                            TotalAmount = 150m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 3,
                            OrderDate = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending",
                            PaymentMethod = "Credit Card",
                            PaymentStatus = "Pending",
                            ShippingAddress = "Quận 9 - TP.HCM",
                            TotalAmount = 200m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 4,
                            OrderDate = new DateTime(2025, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Shipped",
                            PaymentMethod = "COD",
                            PaymentStatus = "Paid",
                            ShippingAddress = "Quận 10 - TP.HCM",
                            TotalAmount = 250m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 5,
                            OrderDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending",
                            PaymentMethod = "Credit Card",
                            PaymentStatus = "Pending",
                            ShippingAddress = "Quận 9 - TP.HCM",
                            TotalAmount = 300m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 6,
                            OrderDate = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Shipped",
                            PaymentMethod = "COD",
                            PaymentStatus = "Pending",
                            ShippingAddress = "Quận 1 - TP.HCM",
                            TotalAmount = 350m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 7,
                            OrderDate = new DateTime(2025, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending",
                            PaymentMethod = "Credit Card",
                            PaymentStatus = "Paid",
                            ShippingAddress = "Quận 1 - TP.HCM",
                            TotalAmount = 400m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 8,
                            OrderDate = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Shipped",
                            PaymentMethod = "COD",
                            PaymentStatus = "Pending",
                            ShippingAddress = "Quận 2 - TP.HCM",
                            TotalAmount = 450m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 9,
                            OrderDate = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending",
                            PaymentMethod = "Credit Card",
                            PaymentStatus = "Pending",
                            ShippingAddress = "Quận 3 - TP.HCM",
                            TotalAmount = 500m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 10,
                            OrderDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Shipped",
                            PaymentMethod = "COD",
                            PaymentStatus = "Paid",
                            ShippingAddress = "Quận 8 - TP.HCM",
                            TotalAmount = 550m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 11,
                            OrderDate = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending",
                            PaymentMethod = "Credit Card",
                            PaymentStatus = "Pending",
                            ShippingAddress = "Quận 11 - TP.HCM",
                            TotalAmount = 600m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 12,
                            OrderDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Shipped",
                            PaymentMethod = "COD",
                            PaymentStatus = "Pending",
                            ShippingAddress = "Quận 6 - TP.HCM",
                            TotalAmount = 650m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 13,
                            OrderDate = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending",
                            PaymentMethod = "Credit Card",
                            PaymentStatus = "Paid",
                            ShippingAddress = "Quận 3 - TP.HCM",
                            TotalAmount = 700m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 14,
                            OrderDate = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Shipped",
                            PaymentMethod = "COD",
                            PaymentStatus = "Pending",
                            ShippingAddress = "Quận 6 - TP.HCM",
                            TotalAmount = 750m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 15,
                            OrderDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending",
                            PaymentMethod = "Credit Card",
                            PaymentStatus = "Pending",
                            ShippingAddress = "Quận 1 - TP.HCM",
                            TotalAmount = 800m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 16,
                            OrderDate = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Shipped",
                            PaymentMethod = "COD",
                            PaymentStatus = "Paid",
                            ShippingAddress = "Quận 11 - TP.HCM",
                            TotalAmount = 850m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 17,
                            OrderDate = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending",
                            PaymentMethod = "Credit Card",
                            PaymentStatus = "Pending",
                            ShippingAddress = "Quận 7 - TP.HCM",
                            TotalAmount = 900m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 18,
                            OrderDate = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Shipped",
                            PaymentMethod = "COD",
                            PaymentStatus = "Pending",
                            ShippingAddress = "Quận 4 - TP.HCM",
                            TotalAmount = 950m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 19,
                            OrderDate = new DateTime(2025, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending",
                            PaymentMethod = "Credit Card",
                            PaymentStatus = "Paid",
                            ShippingAddress = "Quận 1 - TP.HCM",
                            TotalAmount = 1000m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 20,
                            OrderDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Shipped",
                            PaymentMethod = "COD",
                            PaymentStatus = "Pending",
                            ShippingAddress = "Quận 12 - TP.HCM",
                            TotalAmount = 1050m,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("OrderAPI.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderDetailID"));

                    b.Property<int>("OrderID")
                        .HasColumnType("integer");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailID = 1,
                            OrderID = 1,
                            ProductID = 1,
                            Quantity = 4,
                            UnitPrice = 10m
                        },
                        new
                        {
                            OrderDetailID = 2,
                            OrderID = 2,
                            ProductID = 19,
                            Quantity = 3,
                            UnitPrice = 90m
                        },
                        new
                        {
                            OrderDetailID = 3,
                            OrderID = 2,
                            ProductID = 16,
                            Quantity = 1,
                            UnitPrice = 63m
                        },
                        new
                        {
                            OrderDetailID = 4,
                            OrderID = 2,
                            ProductID = 25,
                            Quantity = 4,
                            UnitPrice = 16m
                        },
                        new
                        {
                            OrderDetailID = 5,
                            OrderID = 3,
                            ProductID = 3,
                            Quantity = 4,
                            UnitPrice = 28m
                        },
                        new
                        {
                            OrderDetailID = 6,
                            OrderID = 3,
                            ProductID = 12,
                            Quantity = 4,
                            UnitPrice = 93m
                        },
                        new
                        {
                            OrderDetailID = 7,
                            OrderID = 4,
                            ProductID = 15,
                            Quantity = 1,
                            UnitPrice = 78m
                        },
                        new
                        {
                            OrderDetailID = 8,
                            OrderID = 4,
                            ProductID = 4,
                            Quantity = 1,
                            UnitPrice = 44m
                        },
                        new
                        {
                            OrderDetailID = 9,
                            OrderID = 4,
                            ProductID = 5,
                            Quantity = 2,
                            UnitPrice = 73m
                        },
                        new
                        {
                            OrderDetailID = 10,
                            OrderID = 5,
                            ProductID = 1,
                            Quantity = 3,
                            UnitPrice = 84m
                        },
                        new
                        {
                            OrderDetailID = 11,
                            OrderID = 6,
                            ProductID = 4,
                            Quantity = 3,
                            UnitPrice = 15m
                        },
                        new
                        {
                            OrderDetailID = 12,
                            OrderID = 6,
                            ProductID = 3,
                            Quantity = 2,
                            UnitPrice = 20m
                        },
                        new
                        {
                            OrderDetailID = 13,
                            OrderID = 6,
                            ProductID = 19,
                            Quantity = 1,
                            UnitPrice = 13m
                        },
                        new
                        {
                            OrderDetailID = 14,
                            OrderID = 7,
                            ProductID = 22,
                            Quantity = 1,
                            UnitPrice = 88m
                        },
                        new
                        {
                            OrderDetailID = 15,
                            OrderID = 8,
                            ProductID = 27,
                            Quantity = 2,
                            UnitPrice = 86m
                        },
                        new
                        {
                            OrderDetailID = 16,
                            OrderID = 8,
                            ProductID = 7,
                            Quantity = 1,
                            UnitPrice = 34m
                        },
                        new
                        {
                            OrderDetailID = 17,
                            OrderID = 8,
                            ProductID = 16,
                            Quantity = 3,
                            UnitPrice = 32m
                        },
                        new
                        {
                            OrderDetailID = 18,
                            OrderID = 9,
                            ProductID = 14,
                            Quantity = 2,
                            UnitPrice = 76m
                        },
                        new
                        {
                            OrderDetailID = 19,
                            OrderID = 9,
                            ProductID = 2,
                            Quantity = 2,
                            UnitPrice = 49m
                        },
                        new
                        {
                            OrderDetailID = 20,
                            OrderID = 10,
                            ProductID = 7,
                            Quantity = 1,
                            UnitPrice = 66m
                        },
                        new
                        {
                            OrderDetailID = 21,
                            OrderID = 10,
                            ProductID = 28,
                            Quantity = 1,
                            UnitPrice = 23m
                        },
                        new
                        {
                            OrderDetailID = 22,
                            OrderID = 10,
                            ProductID = 9,
                            Quantity = 2,
                            UnitPrice = 83m
                        },
                        new
                        {
                            OrderDetailID = 23,
                            OrderID = 11,
                            ProductID = 13,
                            Quantity = 1,
                            UnitPrice = 72m
                        },
                        new
                        {
                            OrderDetailID = 24,
                            OrderID = 12,
                            ProductID = 2,
                            Quantity = 3,
                            UnitPrice = 26m
                        },
                        new
                        {
                            OrderDetailID = 25,
                            OrderID = 12,
                            ProductID = 16,
                            Quantity = 2,
                            UnitPrice = 37m
                        },
                        new
                        {
                            OrderDetailID = 26,
                            OrderID = 13,
                            ProductID = 16,
                            Quantity = 3,
                            UnitPrice = 48m
                        },
                        new
                        {
                            OrderDetailID = 27,
                            OrderID = 13,
                            ProductID = 16,
                            Quantity = 2,
                            UnitPrice = 47m
                        },
                        new
                        {
                            OrderDetailID = 28,
                            OrderID = 13,
                            ProductID = 19,
                            Quantity = 1,
                            UnitPrice = 44m
                        },
                        new
                        {
                            OrderDetailID = 29,
                            OrderID = 14,
                            ProductID = 18,
                            Quantity = 3,
                            UnitPrice = 29m
                        },
                        new
                        {
                            OrderDetailID = 30,
                            OrderID = 14,
                            ProductID = 16,
                            Quantity = 4,
                            UnitPrice = 31m
                        },
                        new
                        {
                            OrderDetailID = 31,
                            OrderID = 15,
                            ProductID = 22,
                            Quantity = 1,
                            UnitPrice = 58m
                        },
                        new
                        {
                            OrderDetailID = 32,
                            OrderID = 16,
                            ProductID = 6,
                            Quantity = 1,
                            UnitPrice = 18m
                        },
                        new
                        {
                            OrderDetailID = 33,
                            OrderID = 16,
                            ProductID = 13,
                            Quantity = 3,
                            UnitPrice = 33m
                        },
                        new
                        {
                            OrderDetailID = 34,
                            OrderID = 16,
                            ProductID = 12,
                            Quantity = 4,
                            UnitPrice = 60m
                        },
                        new
                        {
                            OrderDetailID = 35,
                            OrderID = 17,
                            ProductID = 3,
                            Quantity = 1,
                            UnitPrice = 13m
                        },
                        new
                        {
                            OrderDetailID = 36,
                            OrderID = 17,
                            ProductID = 20,
                            Quantity = 3,
                            UnitPrice = 28m
                        },
                        new
                        {
                            OrderDetailID = 37,
                            OrderID = 18,
                            ProductID = 20,
                            Quantity = 3,
                            UnitPrice = 69m
                        },
                        new
                        {
                            OrderDetailID = 38,
                            OrderID = 18,
                            ProductID = 11,
                            Quantity = 2,
                            UnitPrice = 70m
                        },
                        new
                        {
                            OrderDetailID = 39,
                            OrderID = 19,
                            ProductID = 17,
                            Quantity = 2,
                            UnitPrice = 86m
                        },
                        new
                        {
                            OrderDetailID = 40,
                            OrderID = 19,
                            ProductID = 6,
                            Quantity = 2,
                            UnitPrice = 24m
                        },
                        new
                        {
                            OrderDetailID = 41,
                            OrderID = 19,
                            ProductID = 24,
                            Quantity = 1,
                            UnitPrice = 78m
                        },
                        new
                        {
                            OrderDetailID = 42,
                            OrderID = 20,
                            ProductID = 10,
                            Quantity = 3,
                            UnitPrice = 40m
                        });
                });

            modelBuilder.Entity("OrderAPI.Models.OrderDetail", b =>
                {
                    b.HasOne("OrderAPI.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderAPI.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
